---
- name: Create security group All_open
  os_security_group:
    name: "All_open"

- os_security_group_rule:
    security_group: "All_open"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    security_group: "All_open"
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    security_group: "All_open"
    protocol: udp
    remote_ip_prefix: 0.0.0.0/0
...
