---
# Security rules for jenkins master
- name: Create jenkinsmaster secgroup
  os_security_group:
    name: jenkinsmaster
    description: security group for jenkinsmaster

- name: Allow all in private net
  os_security_group_rule:
    security_group: jenkinsmaster
    remote_ip_prefix: "{{ os_net_cidr }}"

- name: HTTP port 8080 access for Jenkins GUI
  os_security_group_rule:
    security_group: jenkinsmaster
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: "{{ item }}"
  loop: "{{ devel_networks }}"
...
