---
- name: Precheck of environment variables
  import_playbook: playbooks/precheck_keypair.yml
  tags: [always]

- name: Precheck of environment variables
  import_playbook: playbooks/precheck_osenv.yml
  tags: [always]

- name: Create instance for jumphost
  hosts: jumphosts
  gather_facts: false
  roles:
    - role: openstack-vm-create
      name: "{{ inventory_hostname }}"
      networks:
        - { name: "{{ os_net_name }}", ip: "{{ mgmt_ip }}" }
      boot_image: "{{ centos_image_name }}"
      flavor: "{{ jump_flavor }}"
      security_groups: "jumphost"
      public_primary_ip: "{{ floating_ip }}"
      ssh_check_username: "centos"
      ssh_check_ip: "{{ floating_ip }}"
      delegate_to: localhost
  tags: [vm]

- name: Configure jumphosts
  hosts: jumphosts
  become: yes
  remote_user: "{{ 'centos' if ((instance is defined and instance.changed==true) or force_centos is defined ) else (omit) }}"
  roles:
    - users
    - openstack-vm-common
    - jumphost-conf
  tags: [conf]
...
