---
- name: Precheck of environment variables
  import_playbook: precheck_osenv.yml
  tags: [always]

- name: Create OpenStack security groups
  hosts: localhost
  roles:
    - role: openstack-secgroups
