---
# NOTE: The key used here is just an example created for demo purposes.
# Do not use the same key in any real environment!
# It corresponds to jenkisci user's public key in group_vars/all/users.yml

jenkinsci_private_key_pw: ""

jenkinsci_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAsJIqe6ILb4pM8NwmGXNbW7fKwmd6/ddPjwptJa2/Z4QFSXZ/
  utqrci+xhKwqbH0f2/oTC00NTDWmKIRNqKaWoQm+DNeK+1ErMqzm7mDcTw/YDkji
  Hhda7vAeYMgVwWaSJDmwz7htFEhqkqSHHdJ8T75S8YGyBfoTQRkgm9ZXTtpG7e4d
  IuZfKjujwFtpOLwjwLJYCld8/R7Ri98ZUTzBrGDZHwJYCcH3AHVXE/G4Z5+IMmMj
  TOoa8B4/11wYi8KKLAuDeGYsmZn8ShJJXiBzleH8WTYtoWTqGAM9/2bRVqWzC6br
  5Fqteamd7mF1Gd6kOYahOYtmXk8j+mS6JdyrCQIDAQABAoIBAGOfxMqG7m7bmHfZ
  rsFzXduNAqDXZASvJBtv5Y95zeHpElaVvpG96Tf/Auj5fuJBYuVp3q7kpZkXOA3q
  QCrk+14XMhzqzGbqMDZiadWb3xHYva2pn7McuFjSMEGpAuVhKxm3VzSMOTdVeJQO
  spG3/h28I+5RoBFRPOXg+I4UzKQXAi89EdBrzkfAmvkMNgJWMiajIN+5MRPUgz9F
  XQVqdKjjgnmZNZHX3D+Im4nmm55me1fbulfQMXNr12rKzfX0BzvRhfw24rf6w2ut
  zCKTsnAaWb6E5b5VaqdYWKEEiy4DItKA1sdCQ15AK7Dk+d+7YN7fXJWQlK+LwUqJ
  HmKEUMUCgYEA2TZba0hdENP+INtI9/cPYIZijANf7pRKs7qr6/kGLwNIHhVrR0OV
  2p8v9VwLEncrZTnm5CvG/8n0scVDq6/uQXXE956f3Q57QN8qGBGzb3PmiGP9izj8
  4CbfCcpDK2AgTuVcghgRq6huqcERwNdStJ8vGezgr2abUayOpRCmt7MCgYEA0Bnt
  8woRILrQkcLpXdVGy0RMy7IoNs2JX3GkMJYP25LSy++xSFixQfTcfMqkIFP0Ga1l
  RFwSIOQeo156UHtqoJ/IoMnPgxvIzFzS20LU1/bGn3beM5KGs64lOMnJXHZSUdqf
  SHnQwp5aztbwhLMN3efIkVayjNFxD97I8VAmdFMCgYADsgwOIDYNIj4xmul75oUp
  dD/a9/e63GUE98kTA7KaPCkO8fhYRwsWpByxxPYfQ03GtBx8h04kbfAu0hdbpWud
  S36lY9p+bU+lg+Z4cFyoKcWjTmgy5S5QNfkXdox8AW+rR/Wx9OzgCcaQNsuxhzhO
  AGNRwpj0Av/jfNcUcdsURwKBgDcjt7XfI/ytI1iL8bPIMDLpzQNoGFm1CkI85Ulu
  aZM/ixU4VJwbzBPy4n06YFSkihhHpn5/eto2N5wIC5bJrM4UqF9aOd6+fO0RZ1lr
  kuQKYkSchXHa0FBJw1kRtoYGX/eKWwwkItl+hgcqUp6GpxT2NmG0PCkt0axn1oyC
  NT47AoGBAKrzUDvG2J81T/uIjZRRtDPK8on07MI9tMSYoCPyNJ5PcCpw4GwWCtad
  d9vJm9xheY6+WYgzgW9tz/S9CsRV2eTkyLOL4o16oAPIyCctF5hKWgF/QHm10NNN
  UeYZN47vOxlVAiMP7Pgu0YZRQmC0J/NEwTPYj+fdZSJzDecSyT70
  -----END RSA PRIVATE KEY-----
