---
# Input for these tasks comes from jenkins_config.yml
- name: Add privatekey credentials to Jenkins
  jenkins_script:
    url: "{{ jenkins_url }}"
    script: "{{ lookup('template', 'templates/add-privatekey-credentials.groovy.j2') }}"
    validate_certs: false
    user:     "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  with_dict: "{{ jenkins_private_key_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.key }}"
  tags:
    - add-credentials
...
