---
# Create openrc files in jumphost

# openrc file for Nebula
- name: Make Nebula cloud config file for admin users
  template:
    src: "templates/nebula_openrc.sh.j2"
    dest: "/home/{{ user.name }}/nebula_openrc.sh"
    owner: "{{ user.name }}"
    force: no
  with_items: "{{ users }}"
  when:
    - inventory_hostname in groups['jumphosts']
    - item.state is undefined or item.state == 'present'
  loop_control:
    label: "{{ user.name }}"
    loop_var: "user"
  tags: [nebula]
...
