---
# Common configuration for all OpenStack VMs
- name: Set timezone
  timezone:
    name: "{{ vm_timezone |default('Europe/Helsinki') }}"

- name: Install EPEL repository
  yum:
    name: epel-release

- name: Install packages
  yum:
    name:
    - tcpdump
    - nano

- import_tasks: nano.yml
  tags: [nano]
